gateway:
  mode: private
  private_token: your-secure-token-here  # Generate a strong random token

http:
  listen: 0.0.0.0:3000

database:
  host: ${{MYSQL_HOST}}
  port: ${{MYSQL_PORT}}
  user: ${{MYSQL_USER}}
  password: ${{MYSQL_PASSWORD}}
  database: ${{MYSQL_DATABASE}}
  timezone: UTC

# Add other configurations as needed