services:
  backend:
    image: capcom6/sms-gateway
    build:
      context: ../..
      dockerfile: ./build/package/Dockerfile
      args:
        - APP=sms-gateway
    environment:
      - DEBUG=
      - CONFIG_PATH=config.yml
      - GOOSE_DBSTRING=/app/data/sms.db?_pragma=foreign_keys(1)
      - HTTP__LISTEN=0.0.0.0:3000
      - DATABASE__DIALECT=sqlite3
      - DATABASE__DATABASE=/app/data/sms.db
    ports:
      - "3000:3000"
    volumes:
      - ../../configs/config.yml:/app/config.yml:ro
      - sqlite-data:/app/data
    restart: 'unless-stopped'

volumes:
  sqlite-data:
